# Drivers
CONFIG_INPUT=y
CONFIG_LED=y
CONFIG_LED_PWM=n
CONFIG_PWM=y

# Bluetooth core
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="Silabs Find Me"
CONFIG_BT_MAX_CONN=1
# Peripheral
CONFIG_BT_PERIPHERAL=y

# Enable HCI error to string conversions
CONFIG_BT_HCI_ERR_TO_STR=y

# Device Information Service (strings only, using enable + _STR pairs)
CONFIG_BT_DIS=y

CONFIG_BT_DIS_MODEL_NUMBER=y
CONFIG_BT_DIS_MODEL_NUMBER_STR="Find Me"

CONFIG_BT_DIS_MANUF_NAME=y
CONFIG_BT_DIS_MANUF_NAME_STR="Silicon Labs"

CONFIG_BT_DIS_SERIAL_NUMBER=y
CONFIG_BT_DIS_SERIAL_NUMBER_STR="123456789"

CONFIG_BT_DIS_FW_REV=y
CONFIG_BT_DIS_FW_REV_STR="1.0.0"

CONFIG_BT_DIS_HW_REV=y
CONFIG_BT_DIS_HW_REV_STR="BRD2601B Rev A01"

CONFIG_BT_DIS_SW_REV=y
CONFIG_BT_DIS_SW_REV_STR="0.2.4"

# Disable the PNP ID characteristic
CONFIG_BT_DIS_PNP=n